### ISSUE TITLE
Create a gateway framework

### ISSUE THREAD

**Issue by Jannis** [edgeandnode/gateway#468]
We want something similar to the indexer-service framework introduced in https://github.com/graphprotocol/indexer-rs/pull/80.

This will require extracting a number of modules from the graph-gateway source code into its own crate. The list below tracks the completion of this:

- [ ] Provider (indexer) discovery (generalize all subgraph-specific bits)
- [x] Gateway block cache (for making queries deterministic)
- [ ] Reporting via Kafka
- [x] Prometheus metrics
- [ ] Indexer selection (generalize all subgraph-specific bits)
- [ ] Indexer status tracking
- [ ] Budgeting & indexer cost tracking
- [ ] GeoIP support

This list may not be complete.

**Comment by LNSD** [comment]
This comment is related to PR #808:

How do you envision a JSON-RPC gateway using a "request selector"?

It's clear to me in the subgraph gateway. One client can pick one subgraph either:
* **By subgraph ID:** The gateway decides the deployment version depending on the indexers' performance info.
* **By deployment ID:** The subgraph version is pinned, and the gateway makes decisions based on indexers' performance info.

Could you explain what needs to be multiplexed and selected in a JSON-RPC gateway?
